# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/mustafasamil.ileri/PycharmProjects/sayi_sistem_donusumu/gui/main_page.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 304)
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 451, 281))
        self.frame.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ceviri_cmbx = QtWidgets.QComboBox(self.frame)
        self.ceviri_cmbx.setGeometry(QtCore.QRect(280, 90, 141, 22))
        self.ceviri_cmbx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ceviri_cmbx.setObjectName("ceviri_cmbx")
        self.ceviri_cmbx.addItem("")
        self.ceviri_cmbx.addItem("")
        self.ceviri_cmbx.addItem("")
        self.ceviri_cmbx.addItem("")
        self.ceviri_cmbx.addItem("")
        self.ceviri_cmbx.addItem("")
        self.ceviri_cmbx.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(270, 60, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 71, 31))
        self.label_5.setObjectName("label_5")
        self.hexadecimal_lne = QtWidgets.QLineEdit(self.frame)
        self.hexadecimal_lne.setGeometry(QtCore.QRect(130, 210, 121, 21))
        self.hexadecimal_lne.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hexadecimal_lne.setObjectName("hexadecimal_lne")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(320, 200, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 0, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.binary_lne = QtWidgets.QLineEdit(self.frame)
        self.binary_lne.setGeometry(QtCore.QRect(130, 120, 121, 21))
        self.binary_lne.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.binary_lne.setObjectName("binary_lne")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.label_3.setObjectName("label_3")
        self.cevir_btn = QtWidgets.QPushButton(self.frame)
        self.cevir_btn.setGeometry(QtCore.QRect(300, 130, 101, 31))
        self.cevir_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cevir_btn.setObjectName("cevir_btn")
        self.decimal_lne = QtWidgets.QLineEdit(self.frame)
        self.decimal_lne.setGeometry(QtCore.QRect(130, 160, 121, 21))
        self.decimal_lne.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.decimal_lne.setObjectName("decimal_lne")
        self.girilen_sayi_lne = QtWidgets.QLineEdit(self.frame)
        self.girilen_sayi_lne.setGeometry(QtCore.QRect(130, 70, 121, 21))
        self.girilen_sayi_lne.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.girilen_sayi_lne.setObjectName("girilen_sayi_lne")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 91, 31))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 454, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ceviri_cmbx.setItemText(0, _translate("MainWindow", "Dec -> Binary"))
        self.ceviri_cmbx.setItemText(1, _translate("MainWindow", "Binary -> Dec"))
        self.ceviri_cmbx.setItemText(2, _translate("MainWindow", "Hex -> Dec"))
        self.ceviri_cmbx.setItemText(3, _translate("MainWindow", "Dec -> Hex"))
        self.ceviri_cmbx.setItemText(4, _translate("MainWindow", "Hex -> Binary"))
        self.ceviri_cmbx.setItemText(5, _translate("MainWindow", "Binary -> Hex"))
        self.ceviri_cmbx.setItemText(6, _translate("MainWindow", "All"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Sayı Sistem Dönüşümü Seç </span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Decimal :</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; color:#ffffff;\">Made by shamiltexh</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Binary :</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Sayı Sistemleri Dönüşümü</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Sayıyı Giriniz : </span></p></body></html>"))
        self.cevir_btn.setText(_translate("MainWindow", "Çevir"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Hexadecimal :</span></p></body></html>"))

